image: node:14

stages:
  - install
  - unit_testing

install:
  stage: install
  script:
    - yarn install
  artifacts:
    expire_in: 1h
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

unit_testing:
  stage: unit_testing
  dependencies:
    - install
  script:
    - yarn run test
